# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# https://www.mkdocs.org/user-guide/configuration/#configuration
site_name: Flight Manual
site_description: Documentation for the Hangar 747 Homelab
site_author: Kevin Kraemer
site_url: https://mydomain.org/flightmanual
repo_name: krake747/hangar-747
repo_url: https://github.com/krake747/hangar-747/tree/main/python/flightmanual
docs_dir: docs
theme:
  name: material
  language: en
  direction: ltr
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: red
      accent: light blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
