FROM python:3.13-slim

WORKDIR /src

RUN pip install uv

COPY ./bw-docs/requirements.txt /src/requirements.txt
RUN uv pip install -r requirements.txt --system

COPY ./bw-docs/mkdocs.yml /src/mkdocs.yml
# For the compose.yml bind mounts
RUN mkdir -p /src/docs

EXPOSE 8000

ENTRYPOINT ["mkdocs"]
CMD ["serve", "--dev-addr=0.0.0.0:8000"]
