FROM python:3.13-slim

WORKDIR /src

COPY ./bw-docs/requirements.txt /src/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./bw-docs/mkdocs.yml /src/mkdocs.yml
# For the compose.yml bind mounts
RUN mkdir -p /src/docs

EXPOSE 8000

ENTRYPOINT ["mkdocs"]
CMD ["serve", "--dev-addr=0.0.0.0:8000"]
