# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# https://www.mkdocs.org/user-guide/configuration/#configuration
site_name: Bueno Wind Docs
site_description: Documentation for Bueno Wind
site_author: Kevin Kraemer
site_url: https://mydomain.org/buenowind-docs
repo_name: krake747/hangar-747
repo_url: https://github.com/krake747/hangar-747/tree/main/apps/buenowind/
theme:
  name: material
  language: en
  direction: ltr
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: red
      accent: light blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - tags

markdown_extensions:
  # admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # code snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # images
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  # content tabs
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: README.md
  - Theory:
      - Basics:
          - basics/index.md
          - basics/one-way-binding.md
          - basics/two-way-binding.md
          - basics/template-variable.md
          - basics/embedded-templates.md
          - basics/control-flow-syntax.md
          - basics/decorators.md
          - basics/directives.md
          - basics/components.md
          - basics/input-and-output.md
          - basics/signals.md
      - Angular:
          - angular/index.md
          - angular/standalones.md
          - angular/template-context.md
          - angular/injectables.md
          - angular/injector-hierarchy.md
          - angular/function-based-logic.md
          - angular/dependency-injection.md
          - angular/change-detection.md
          - angular/dependency-injection.md
          - angular/navigation-between-routes.md
          - angular/fetching-data-from-api.md
          - angular/reactive-forms.md
      - Eager vs lazy:
          - eager-vs-lazy/index.md
          - eager-vs-lazy/eager-part.md
          - eager-vs-lazy/lazy-part.md
          - eager-vs-lazy/routing-based-lazy-loading.md
          - eager-vs-lazy/defer-based-lazy-loading.md
      - Signal APIs:
          - signal-apis/index.md
          - signal-apis/writable-signal.md
          - signal-apis/computed.md
          - signal-apis/effect.md
          - signal-apis/input.md
          - signal-apis/output.md
          - signal-apis/view-queries.md
          - signal-apis/content-queries.md
          - signal-apis/model.md
          - signal-apis/resource.md
          - signal-apis/rx-resource.md
          - signal-apis/http-resource.md
          - signal-apis/linked-signal.md
      - RxJS:
          - rxjs/index.md
          - rxjs/reactive-programming-analogy.md
          - rxjs/declarative-and-reactive-coding.md
          - rxjs/observables.md
          - rxjs/observer-pattern.md
          - rxjs/subjects.md
          - rxjs/commonly-used-operators.md
          - rxjs/creation-operators.md
          - rxjs/higher-order-observables.md
          - rxjs/flattening-operators.md
  - Key Concepts:
      - Lazy Loading:
          - lazy-loading/index.md
          - lazy-loading/faster-startup-time-for-users.md
          - lazy-loading/faster-developer-feedback-loop.md
          - lazy-loading/isolation-benefit.md
          - lazy-loading/heuristics.md
      - Isolation:
          - isolation/index.md
          - isolation/local-impact.md
          - isolation/extensibility-and-evolution-of-the-code-base.md
          - isolation/features-as-a-black-box.md
      - One Way Dependency Graph:
          - one-way-dependency-graph/index.md
      - State Management:
          - state-management/index.md
          - state-management/rxjs-and-signals.md
  - Implementation Hints:
      - State vs View logic:
          - state-vs-view-logic/index.md
      - Correct level of abstraction:
          - correct-level-of-abstraction/index.md
          - correct-level-of-abstraction/framework-vs-application-business-logic.md
          - correct-level-of-abstraction/short-term-vs-long-term-thinking.md
          - correct-level-of-abstraction/optimizing-for-the-wrong-thing.md
          - correct-level-of-abstraction/common-negative-consequences-of-adding-abstractions.md
          - correct-level-of-abstraction/correct-level-of-technical-abstraction.md
          - correct-level-of-abstraction/how-to-handle-verbosity.md
  - The Big Picture:
      - the-big-picture/index.md
      - the-big-picture/app.md
      - the-big-picture/main.md
      - Core:
          - core/index.md
          - core/standalone-core.md
          - core/grouping-core-logic-in-folders-per-domain.md
      - Layout:
          - layout/index.md
          - layout/single-layout.md
          - layout/multiple-layouts.md
          - layout/custom-layout-per-feature.md
      - UI:
          - ui/index.md
          - ui/standalones-only.md
          - ui/generic-reuseable-ui-components.md
          - ui/eager-vs-lazy-bundling-implications.md
          - ui/how-to-handle-types-and-interfaces.md
          - ui/how-to-handle-complex-pipes.md
      - Feature:
          - feature/index.md
          - feature/black-box-nature.md
          - feature/fractal-nature.md
          - feature/nested-lazy-sub-features.md
          - feature/sharing-logic-between-lazy-features.md
          - feature/sharing-features.md
      - Pattern:
          - pattern/index.md
          - pattern/pattern-vs-ui-core-feature.md
          - pattern/when-to-create-a-pattern.md
      - the-big-picture/relationship-between-types.md
      - the-big-picture/most-common-dependency-graph-issues.md
