name: "{{package}}"

on:
  push:
    paths:
      - "golang/{{package}}/**"
      - ".github/workflows/go-{{package}}.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.5"
          cache: false

      - name: Go version
        run: go version

      - name: Install dependencies
        run: |-
          cd golang/{{package}}
          make deps

      - name: Run tests
        run: |-
          cd golang/{{package}}
          go test -v ./...
