name: Deploy Infrastructure to Azure

on:
  push:
    branches:
      - main
    paths:
      - "infra/azure/**"
      - ".github/workflows/deploy-infra-to-azure.yml"

concurrency:
  group: infra-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  deploy-infra-to-azure:
    runs-on: ubuntu-latest
    environment: azure-production
    defaults:
      run:
        working-directory: infra/azure
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: "1.10.7"

      - name: Check State Lock
        run: |
          set -euo pipefail
          az storage blob show \
            --account-name krakeiacfiles \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --container-name terraform \
            --name terraform.tfstate \
            --query properties.lease

      - name: Check OpenTofu Format
        run: tofu fmt -check

      - name: Init OpenTofu
        run: tofu init

      - name: Validate Config
        run: tofu validate

      - name: Plan Changes
        env:
          TF_VAR_subscription_id: ${{ env.ARM_SUBSCRIPTION_ID }}
        run: tofu plan -out=tfplan -lock-timeout=30s -input=false

      - name: Apply Changes
        run: tofu apply -auto-approve tfplan
