version: "2"

run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - unused
    - lll

  settings:
    lll:
      line-length: 120
      tab-width: 1

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      module-path: bookstore2
      extra-rules: true
