version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - lll

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      module-path: bookstore2
      extra-rules: true
