run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - unused
    - lll

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: bookstore2
  lll:
    line-length: 120

issues:
  exclude-use-default: false