apiVersion: v1
kind: Service
metadata:
  labels:
    app: skyconvert
  name: skyconvert
  namespace: hangar-747
spec:
  ports:
    - port: 7001
      protocol: TCP
      targetPort: 8080
  selector:
    app: skyconvert
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: skyconvert
  name: skyconvert
  namespace: hangar-747
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skyconvert
  strategy: {}
  template:
    metadata:
      labels:
        app: skyconvert
    spec:
      containers:
        - image: skyconvert-api:latest
          name: skyconvert-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: Networking__SkyOps
              valueFrom:
                configMapKeyRef:
                  name: skyops
                  key: Networking__SkyOps
            - name: Networking__SkyConvert
              valueFrom:
                configMapKeyRef:
                  name: skyops
                  key: Networking__SkyConvert
          volumeMounts:
            - name: thumbnails-volume
              mountPath: /thumbnails
      volumes:
        - name: thumbnails-volume
          emptyDir: {}
status: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skyconvert
  namespace: hangar-747
data:
  Networking__SkyOps: "http://skyops.hangar-747.svc.cluster.local:7000/"
  Networking__SkyConvert: "http://skyconvert.hangar-747.svc.cluster.local:7001/"
