apiVersion: v1
kind: Service
metadata:
  labels:
    app: skyops
  name: skyops
  namespace: hangar-747
spec:
  ports:
    - port: 7000
      protocol: TCP
      targetPort: 8080
  selector:
    app: skyops
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: skyops
  name: skyops
  namespace: hangar-747
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skyops
  strategy: {}
  template:
    metadata:
      labels:
        app: skyops
    spec:
      containers:
        - image: skyops-api:latest
          name: skyops-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: Networking__SkyOps
              valueFrom:
                configMapKeyRef:
                  name: skyops
                  key: Networking__SkyOps
            - name: Networking__SkyConvert
              valueFrom:
                configMapKeyRef:
                  name: skyops
                  key: Networking__SkyConvert
status: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skyops
  namespace: hangar-747
data:
  Networking__SkyOps: "http://skyops.hangar-747.svc.cluster.local:7000/"
  Networking__SkyConvert: "http://skyconvert.hangar-747.svc.cluster.local:7001/"
