name: hangar-747

services:
  buenowind.docs:
    develop:
      watch:
        - action: sync
          path: ./bw-docs/mkdocs.yml
          target: /src/mkdocs.yml
        - action: sync
          path: ./bw-docs/docs
          target: /src/docs
